const ownerFaker = [
  {
    name: "Ether Tech",
    email: "ether@tech.com",
    userType: "CRM_EDITOR",
    birthDate: "1994-09-08T12:51:13.619Z",
    country: "Bangladesh",
    city: "Dhaka",
    phoneNumber: "01849635870",
    occupation: "Business",
    designation: "NA",
    password: "$2b$12$HqM2FcRFkdSgKPjHmSwMAuOPE9WoMChRuKJBY6zPV0JZYTkUDDTRG",
    location: "Gulshan",
    residenceAddress: "10/4, Road 4, Gulshan 1, Dhaka",
    nid: "6546328535",
    status: true,
  },
  {
    name: "Webable Digital",
    email: "webable@digital.com",
    userType: "BUSINESS_OWNER",
    birthDate: "1993-09-08T12:51:13.619Z",
    country: "Bangladesh",
    city: "Dhaka",
    phoneNumber: "01849635879",
    occupation: "Business",
    designation: "NA",
    password: "$2b$12$HqM2FcRFkdSgKPjHmSwMAuOPE9WoMChRuKJBY6zPV0JZYTkUDDTRG",
    location: "Gulshan",
    residenceAddress: "10/4, Road 4, Gulshan 1, Dhaka",
    nid: "6546328535",
    status: true,
  },
  {
    name: "Tech Solutions",
    email: "info@techsolutions.com",
    userType: "BUSINESS_OWNER",
    birthDate: "1988-05-12T09:15:10.119Z",
    country: "Bangladesh",
    city: "Chittagong",
    phoneNumber: "01789453621",
    occupation: "IT Services",
    designation: "CEO",
    password: "$2b$12$HqM2FcRFkdSgKPjHmSwMAuOPE9WoMChRuKJBY6zPV0JZYTkUDDTRG",
    location: "Agrabad",
    residenceAddress: "25/3, Agrabad, Chittagong",
    nid: "1234567890",
    status: true,
  },
  {
    name: "Urban Solutions",
    email: "contact@urbansolutions.com",
    userType: "BUSINESS_OWNER",
    birthDate: "1992-07-21T15:10:45.217Z",
    country: "Bangladesh",
    city: "Sylhet",
    phoneNumber: "01845673245",
    occupation: "Marketing",
    designation: "Manager",
    password: "$2b$12$HqM2FcRFkdSgKPjHmSwMAuOPE9WoMChRuKJBY6zPV0JZYTkUDDTRG",
    location: "Zindabazar",
    residenceAddress: "11/5, Zindabazar, Sylhet",
    nid: "9876543210",
    status: true,
  },
  {
    name: "Digital Hive",
    email: "hello@digitalhive.com",
    userType: "BUSINESS_OWNER",
    birthDate: "1995-03-18T13:30:22.919Z",
    country: "Bangladesh",
    city: "Rajshahi",
    phoneNumber: "01987654321",
    occupation: "Digital Marketing",
    designation: "Director",
    password: "$2b$12$HqM2FcRFkdSgKPjHmSwMAuOPE9WoMChRuKJBY6zPV0JZYTkUDDTRG",
    location: "New Market",
    residenceAddress: "17/9, New Market, Rajshahi",
    nid: "4567890123",
    status: true,
  },
  {
    name: "Synergy Corp",
    email: "synergy@corp.com",
    userType: "BUSINESS_OWNER",
    birthDate: "1990-11-03T10:20:33.719Z",
    country: "Bangladesh",
    city: "Khulna",
    phoneNumber: "01756783254",
    occupation: "Corporate Services",
    designation: "Coordinator",
    password: "$2b$12$HqM2FcRFkdSgKPjHmSwMAuOPE9WoMChRuKJBY6zPV0JZYTkUDDTRG",
    location: "Sonadanga",
    residenceAddress: "8/2, Sonadanga, Khulna",
    nid: "6540983217",
    status: true,
  },
  {
    name: "Innova Dynamics",
    email: "info@innovadynamics.com",
    userType: "BUSINESS_OWNER",
    birthDate: "1993-02-24T08:45:29.019Z",
    country: "Bangladesh",
    city: "Dhaka",
    phoneNumber: "01833456789",
    occupation: "Product Development",
    designation: "Lead Developer",
    password: "$2b$12$HqM2FcRFkdSgKPjHmSwMAuOPE9WoMChRuKJBY6zPV0JZYTkUDDTRG",
    location: "Banani",
    residenceAddress: "12/7, Banani, Dhaka",
    nid: "3210987654",
    status: true,
  },
  {
    name: "Proactive Solutions",
    email: "contact@proactivesol.com",
    userType: "BUSINESS_OWNER",
    birthDate: "1991-04-15T18:20:50.319Z",
    country: "Bangladesh",
    city: "Barisal",
    phoneNumber: "01765678923",
    occupation: "Consulting",
    designation: "Consultant",
    password: "$2b$12$HqM2FcRFkdSgKPjHmSwMAuOPE9WoMChRuKJBY6zPV0JZYTkUDDTRG",
    location: "Bell's Park",
    residenceAddress: "9/5, Bell's Park, Barisal",
    nid: "7654321890",
    status: true,
  },
  {
    name: "Data Nexus",
    email: "info@datanexus.com",
    userType: "BUSINESS_OWNER",
    birthDate: "1989-09-29T11:35:44.519Z",
    country: "Bangladesh",
    city: "Dhaka",
    phoneNumber: "01999876543",
    occupation: "Data Analysis",
    designation: "Analyst",
    password: "$2b$12$HqM2FcRFkdSgKPjHmSwMAuOPE9WoMChRuKJBY6zPV0JZYTkUDDTRG",
    location: "Motijheel",
    residenceAddress: "15/6, Motijheel, Dhaka",
    nid: "4321098765",
    status: true,
  },
  {
    name: "Insight Solutions",
    email: "contact@insightsol.com",
    userType: "BUSINESS_OWNER",
    birthDate: "1996-06-14T14:50:32.119Z",
    country: "Bangladesh",
    city: "Comilla",
    phoneNumber: "01812345678",
    occupation: "Market Research",
    designation: "Researcher",
    password: "$2b$12$HqM2FcRFkdSgKPjHmSwMAuOPE9WoMChRuKJBY6zPV0JZYTkUDDTRG",
    location: "Kandirpar",
    residenceAddress: "6/3, Kandirpar, Comilla",
    nid: "6543217890",
    status: true,
  },
  {
    name: "Zenith Works",
    email: "zenith@zenithworks.com",
    userType: "BUSINESS_OWNER",
    birthDate: "1987-12-17T09:05:16.719Z",
    country: "Bangladesh",
    city: "Dhaka",
    phoneNumber: "01911122334",
    occupation: "Manufacturing",
    designation: "Supervisor",
    password: "$2b$12$HqM2FcRFkdSgKPjHmSwMAuOPE9WoMChRuKJBY6zPV0JZYTkUDDTRG",
    location: "Tejgaon",
    residenceAddress: "7/1, Tejgaon, Dhaka",
    nid: "9871234567",
    status: true,
  },
];

const amenityFaker = [
  {
    name: "Wifi",
    icon: "https://www.svgrepo.com/show/61290/wifi-logo.svg",
    price: 0,
    status: true,
  },
  {
    name: "Parking",
    icon: "https://www.svgrepo.com/show/489318/parking.svg",
    price: 0,
    status: true,
  },
  {
    name: "Laundry",
    icon: "https://www.svgrepo.com/show/455913/laundry-service.svg",
    price: 0,
    status: true,
  },
  {
    name: "Air Conditioning",
    icon: "https://www.svgrepo.com/show/288102/air-conditioning-air-conditioner.svg",
    price: 0,
    status: true,
  },
  {
    name: "Cafe",
    icon: "https://www.svgrepo.com/show/452760/cafe.svg",
    price: 0,
    status: true,
  },
  {
    name: "Spa",
    icon: "https://www.svgrepo.com/show/340410/hospital-bed.svg",
    price: 0,
    status: true,
  },
  {
    name: "Security",
    icon: "https://www.svgrepo.com/show/519137/security.svg",
    price: 0,
    status: true,
  },
  {
    name: "Playground",
    icon: "https://www.svgrepo.com/show/236545/basketball.svg",
    price: 0,
    status: true,
  },
  {
    name: "Package lockers",
    icon: "https://www.svgrepo.com/show/114082/lockers.svg",
    price: 0,
    status: true,
  },
  {
    name: "Washer and dryer",
    icon: "https://www.svgrepo.com/show/339667/washer.svg",
    price: 0,
    status: true,
  },
  {
    name: "Swimming pool",
    icon: "https://www.svgrepo.com/show/18559/swimming-pool.svg",
    price: 0,
    status: true,
  },
  {
    name: "Package lockers",
    icon: "https://www.svgrepo.com/show/114082/lockers.svg",
    price: 0,
    status: true,
  },
  {
    name: "Conference Hall",
    icon: "https://www.svgrepo.com/show/68796/conference-hall.svg",
    price: 0,
    status: true,
  },
  {
    name: "Cafeteria",
    icon: "https://www.svgrepo.com/show/311854/cafeteria.svg",
    price: 0,
    status: true,
  },
  {
    name: "Elevator",
    icon: "https://www.svgrepo.com/show/450831/elevator.svg",
    price: 0,
    status: true,
  },
];

const cuisineFaker = [
  { name: "Indian", status: true },
  { name: "Bangla", status: true },
  { name: "Chinese", status: true },
  { name: "Italian", status: true },
  { name: "Thai", status: true },
  { name: "Mexican", status: true },
  { name: "French", status: true },
];

const slotData = [
  {
    sunday: [
      { slottime: "9 AM", status: true },
      { slottime: "10 AM", status: true },
      { slottime: "11 AM", status: true },
      { slottime: "12 PM", status: true },
      { slottime: "2 PM", status: true },
      { slottime: "3 PM", status: true },
      { slottime: "4 PM", status: true },
    ],
  },
  {
    monday: [
      { slottime: "9 AM", status: true },
      { slottime: "10 AM", status: true },
      { slottime: "11 AM", status: true },
      { slottime: "12 PM", status: true },
      { slottime: "2 PM", status: true },
      { slottime: "3 PM", status: true },
      { slottime: "4 PM", status: true },
    ],
  },
  {
    tuesday: [
      { slottime: "9 AM", status: true },
      { slottime: "10 AM", status: true },
      { slottime: "11 AM", status: true },
      { slottime: "12 PM", status: true },
      { slottime: "2 PM", status: true },
      { slottime: "3 PM", status: true },
      { slottime: "4 PM", status: true },
    ],
  },
  {
    wednesday: [
      { slottime: "9 AM", status: true },
      { slottime: "10 AM", status: true },
      { slottime: "11 AM", status: true },
      { slottime: "12 PM", status: true },
      { slottime: "2 PM", status: true },
      { slottime: "3 PM", status: true },
      { slottime: "4 PM", status: true },
    ],
  },
  {
    thursday: [
      { slottime: "9 AM", status: true },
      { slottime: "10 AM", status: true },
      { slottime: "11 AM", status: true },
      { slottime: "12 PM", status: true },
      { slottime: "2 PM", status: true },
      { slottime: "3 PM", status: true },
      { slottime: "4 PM", status: true },
    ],
  },
];
const listingsFaker = [
  {
    type: "RESTAURANT",
    listingName: "Ashita Bar",
    title: "Ashita Bar and Restaurant",
    subTitle: "Drink Zone",
    ownerId: 2,
    logo: "https://img.freepik.com/premium-vector/free-vector-white-vintage-restaurant-logo_883906-2549.jpg",
    sectSymb: 0,
    priority: 100,
    images: [
      {
        link: "https://i.pinimg.com/736x/4d/69/40/4d6940b2144f5d7338c65b27da21c394.jpg",
        precedence: 1,
      },
      {
        link: "https://i.pinimg.com/564x/4b/28/97/4b28976ff4701042266192be7970b927.jpg",
        precedence: 2,
      },
      {
        link: "https://www.shutterstock.com/image-photo/asian-food-background-various-ingredients-260nw-1408028237.jpg",
        precedence: 3,
      },
      {
        link: "https://res.cloudinary.com/dlhkab3aj/image/upload/v1724506452/Untitled_design_1_qykevx.png",
        precedence: 4,
      },
    ],
    slot: slotData,
    offday: [
      { dayname: "friday", from: "9 AM", to: "3 PM" },
      { dayname: "saturday", from: "9 AM", to: "4 PM" },
    ],
    terms:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    cuisines: ["Indian", "Italian", "Thai"],
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    reservationCategory: "TABLE",
    status: true,
  },
  {
    type: "RESTAURANT",
    listingName: "Flavors Fusion",
    title: "Flavors Fusion Diner",
    subTitle: "A Taste of the World",
    ownerId: 3,
    logo: "https://marketplace.canva.com/EAFyXLRB7G4/1/0/1600w/canva-yellow-white-emblem-restaurant-logo-ZFF3o_o-wfs.jpg",
    sectSymb: 0,
    priority: 100,
    images: [
      {
        link: "https://t3.ftcdn.net/jpg/02/05/87/60/360_F_205876015_hYYs7ugqoU8QAobSS3TbnGQ92qyS5gEc.jpg",
        precedence: 1,
      },
      {
        link: "https://t3.ftcdn.net/jpg/07/52/70/26/360_F_752702693_UcYNYcWgDY5fEwG3xN7j5iwFIPQGC3jx.jpg",
        precedence: 2,
      },
    ],
    slot: slotData,
    offday: [{ dayname: "saturday", from: "10 AM", to: "2 PM" }],
    terms:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    cuisines: ["Mexican", "French"],
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    reservationCategory: "TABLE",
    status: true,
  },
  {
    type: "RESTAURANT",
    listingName: "Taste Haven",
    title: "Taste Haven Bistro",
    subTitle: "Where Flavors Unite",
    ownerId: 4,
    logo: "https://i.pinimg.com/736x/eb/4f/74/eb4f749fd1c95eefe5cccbcd325d8299.jpg",
    sectSymb: 0,
    priority: 100,
    images: [
      {
        link: "https://png.pngtree.com/thumb_back/fh260/background/20240425/pngtree-top-desk-with-blur-restaurant-background-wooden-table-image_15665383.jpg",
        precedence: 1,
      },
      {
        link: "https://thumbs.dreamstime.com/b/night-scene-empty-table-restaurant-background-ads-wooden-foreground-blurred-creating-stylish-ideal-space-food-323912615.jpg",
        precedence: 2,
      },
    ],
    slot: slotData,
    offday: [{ dayname: "saturday", from: "10 AM", to: "2 PM" }],
    terms:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    cuisines: ["Mexican", "French"],
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    reservationCategory: "TABLE",
    status: true,
  },
  {
    type: "RESTAURANT",
    listingName: "Sizzle & Spice",
    title: "Sizzle & Spice Grill",
    subTitle: "For the Love of Spice",
    ownerId: 3,
    logo: "https://png.pngtree.com/template/20200704/ourmid/pngtree-restaurant-logo-design-vector-template-image_388753.jpg",
    sectSymb: 0,
    priority: 100,
    images: [
      {
        link: "https://img.freepik.com/photos-premium/scene-restaurant-nuit-table-bois-vide-flou_31965-621763.jpg",
        precedence: 1,
      },
      {
        link: "https://t4.ftcdn.net/jpg/02/94/26/33/360_F_294263329_1IgvqNgDbhmQNgDxkhlW433uOFuIDar4.jpg",
        precedence: 2,
      },
    ],
    slot: slotData,
    offday: [{ dayname: "saturday", from: "10 AM", to: "2 PM" }],
    terms:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    cuisines: ["Mexican", "French"],
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    reservationCategory: "TABLE",
    status: true,
  },
  {
    type: "RESTAURANT",
    listingName: "Urban Bites",
    title: "Urban Bites Café",
    subTitle: "City's Favorite Hangout",
    ownerId: 2,
    logo: "https://img.freepik.com/premium-vector/beautiful-unique-logo-design-food-restaurant-company_1317464-7042.jpg",
    sectSymb: 0,
    priority: 100,
    images: [
      {
        link: "https://png.pngtree.com/thumb_back/fh260/background/20230706/pngtree-3d-render-of-the-interior-of-a-cozy-cafe-restaurant-image_3811953.jpg",
        precedence: 1,
      },
      {
        link: "https://png.pngtree.com/thumb_back/fh260/background/20230707/pngtree-d-render-of-a-dining-space-in-a-restaurant-or-coffee-image_3810268.jpg",
        precedence: 2,
      },
    ],
    slot: slotData,
    offday: [{ dayname: "saturday", from: "10 AM", to: "2 PM" }],
    terms:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    cuisines: ["Mexican", "French"],
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    reservationCategory: "TABLE",
    status: true,
  },
  {
    type: "RESTAURANT",
    listingName: "The Gourmet Corner",
    title: "The Gourmet Corner",
    subTitle: "Indulge in Luxury",
    ownerId: 4,
    logo: "https://img.freepik.com/premium-vector/restaurant-logo-design-vector-illustration-food-symbol-vector_1236506-726.jpg",
    sectSymb: 0,
    priority: 100,
    images: [
      {
        link: "https://img.freepik.com/premium-photo/blurry-background-typical-restaurant-with-centered-generative-ai_681945-32513.jpg",
        precedence: 1,
      },
      {
        link: "https://img.staticmb.com/mbcontent/images/crop/uploads/2024/6/vastu-tips-for-restaurant%20(1)_0_1200.jpg",
        precedence: 2,
      },
    ],
    slot: slotData,
    offday: [{ dayname: "saturday", from: "10 AM", to: "2 PM" }],
    terms:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    cuisines: ["Mexican", "French"],
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    reservationCategory: "TABLE",
    status: true,
  },
  {
    type: "RESTAURANT",
    listingName: "Herb & Soul",
    title: "Herb & Soul Eatery",
    subTitle: "Farm-to-Table Fresh",
    ownerId: 3,
    logo: "https://i.pinimg.com/736x/eb/4f/74/eb4f749fd1c95eefe5cccbcd325d8299.jpg",
    sectSymb: 0,
    priority: 100,
    images: [
      {
        link: "https://img.freepik.com/premium-photo/table-restaurant-with-lights-background_192217-793.jpg",
        precedence: 1,
      },
      {
        link: "https://thumbs.dreamstime.com/b/night-scene-empty-table-restaurant-background-ads-wooden-foreground-blurred-creating-stylish-ideal-space-food-323912615.jpg",
        precedence: 2,
      },
    ],
    slot: slotData,
    offday: [{ dayname: "saturday", from: "10 AM", to: "2 PM" }],
    terms:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    cuisines: ["Mexican", "French"],
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    reservationCategory: "TABLE",
    status: true,
  },
  {
    type: "RESTAURANT",
    listingName: "Crave Kitchen",
    title: "Crave Kitchen & Bar",
    subTitle: "For the Hungry Souls",
    ownerId: 2,
    logo: "https://i.pinimg.com/736x/8b/78/d4/8b78d4f191990af2dbedcf9c30480581.jpg",
    sectSymb: 0,
    priority: 100,
    images: [
      {
        link: "https://png.pngtree.com/thumb_back/fh260/background/20230416/pngtree-burger-restaurant-food-background-image_2409560.jpg",
        precedence: 1,
      },
      {
        link: "https://img.freepik.com/premium-photo/restaurant-background-images-copy-space_1179130-739377.jpg",
        precedence: 2,
      },
    ],
    slot: slotData,
    offday: [{ dayname: "saturday", from: "10 AM", to: "2 PM" }],
    terms:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    cuisines: ["Mexican", "French"],
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    reservationCategory: "TABLE",
    status: true,
  },
  {
    type: "RESTAURANT",
    listingName: "Echo Deli",
    title: "Echo Deli and Café",
    subTitle: "Echoing Great Taste",
    ownerId: 5,
    logo: "https://i.pinimg.com/736x/8b/78/d4/8b78d4f191990af2dbedcf9c30480581.jpg",
    sectSymb: 0,
    priority: 100,
    images: [
      {
        link: "https://img.freepik.com/premium-photo/restaurant-background-images-copy-space_1179130-739859.jpg",
        precedence: 1,
      },
      {
        link: "https://img.freepik.com/premium-photo/restaurant-background-images-copy-space_1179130-739760.jpg",
        precedence: 2,
      },
    ],
    slot: slotData,
    offday: [{ dayname: "saturday", from: "10 AM", to: "2 PM" }],
    terms:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    cuisines: ["Mexican", "French"],
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    reservationCategory: "TABLE",
    status: true,
  },
  {
    type: "RESTAURANT",
    listingName: "The Spice Rack",
    title: "The Spice Rack Bistro",
    subTitle: "A Symphony of Flavors",
    ownerId: 5,
    logo: "https://img.freepik.com/premium-vector/beautiful-unique-logo-design-food-restaurant-company_1317464-7042.jpg",
    sectSymb: 0,
    priority: 100,
    images: [
      {
        link: "https://png.pngtree.com/thumb_back/fh260/background/20231004/pngtree-coffee-shop-and-cafe-lounge-restaurant-an-immersive-3d-rendering-image_13511704.png",
        precedence: 1,
      },
      {
        link: "https://t4.ftcdn.net/jpg/03/80/73/59/360_F_380735933_5lNGw2IABuJMNU5JqIi9RYAFgdQ97U13.jpg",
        precedence: 2,
      },
    ],
    slot: slotData,
    offday: [{ dayname: "saturday", from: "10 AM", to: "2 PM" }],
    terms:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    cuisines: ["Mexican", "French"],
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    reservationCategory: "TABLE",
    status: true,
  },
  {
    type: "RESTAURANT",
    listingName: "Celestial Eats",
    title: "Celestial Eats Lounge",
    subTitle: "Out of This World",
    ownerId: 6,
    logo: "https://img.freepik.com/vector-gratis/plantilla-logo-restaurante_23-2149493624.jpg",
    sectSymb: 0,
    priority: 100,
    images: [
      {
        link: "https://i.pinimg.com/236x/72/dd/82/72dd825a5ae97d820a8b82de5a99979d.jpg",
        precedence: 1,
      },
      {
        link: "https://i.pinimg.com/736x/10/e2/e2/10e2e2667d0c92a73408d1127b5be6a8.jpg",
        precedence: 2,
      },
    ],
    slot: slotData,
    offday: [{ dayname: "saturday", from: "10 AM", to: "2 PM" }],
    terms:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    cuisines: ["Mexican", "French"],
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    reservationCategory: "TABLE",
    status: true,
  },
];

const brachFaker = [
  {
    branchName: "Dhanmondi 32",
    propertyId: 2,
    ownerId: 3,
    area: "Dhanmondi",
    city: "Dhaka",
    country: "Bangladesh",
    images: [
      {
        link: "https://t3.ftcdn.net/jpg/03/24/73/92/360_F_324739203_keeq8udvv0P2h1MLYJ0GLSlTBagoXS48.jpg",
        precedence: 1,
      },
      {
        link: "https://res.cloudinary.com/dlhkab3aj/image/upload/v1724506452/Untitled_design_1_qykevx.png",
        precedence: 2,
      },
    ],
    amenities: [
      {
        icon: "https://www.svgrepo.com/show/61290/wifi-logo.svg",
        name: "Wifi",
      },
      {
        icon: "https://www.svgrepo.com/show/61290/wifi-logo.svg",
        name: "Parking",
      },
    ],
    amenity: ["Wifi", "Parking"],
    location: "https://maps.app.goo.gl/4sS7kLSBjkV3Rcnf9",
    latitude: "23.751547",
    longitude: "90.373464",
    level: "5th",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    terms:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    status: true,
  },
  {
    branchName: "Gulshan 1",
    propertyId: 3,
    ownerId: 4,
    area: "Gulshan",
    city: "Dhaka",
    country: "Bangladesh",
    images: [
      {
        link: "https://e0.pxfuel.com/wallpapers/670/921/desktop-wallpaper-restaurant-png-transparent-restaurant-png-restaurants.jpg",
        precedence: 1,
      },
      {
        link: "https://media-cdn.tripadvisor.com/media/photo-s/0b/e7/4b/e3/week.jpg",
        precedence: 2,
      },
    ],
    amenities: [
      {
        icon: "https://www.svgrepo.com/show/61290/wifi-logo.svg",
        name: "Wifi",
      },
      {
        icon: "https://www.svgrepo.com/show/455913/laundry-service.svg",
        name: "Laundry",
      },
    ],
    amenity: ["Wifi", "Laundry"],
    location: "https://maps.app.goo.gl/sHbMQU7tsJdjuuzc7",
    latitude: "23.7800762",
    longitude: "90.4146065",
    level: "10th",
    description: "Known for its luxury and convenience in Gulshan.",
    terms: "Standard terms apply.",
    status: true,
  },
  {
    branchName: "Banani Plaza",
    propertyId: 4,
    ownerId: 3,
    area: "Banani",
    city: "Dhaka",
    country: "Bangladesh",
    images: [
      {
        link: "https://cdn.arabsstock.com/uploads/images/221154/image-221154-restaurant-cafe-hall-attractive-decorations-colors-high-e-preview.jpg",
        precedence: 1,
      },
      {
        link: "https://cdn.arabsstock.com/uploads/images/140872/image-140872-restaurant-cafe-hall-attractive-decor-colours-upscale-int-preview.jpg",
        precedence: 2,
      },
    ],
    amenities: [
      {
        icon: "https://www.svgrepo.com/show/489318/parking.svg",
        name: "Parking",
      },
      {
        icon: "https://www.svgrepo.com/show/340410/hospital-bed.svg",
        name: "Spa",
      },
    ],
    amenity: ["Parking", "Spa"],
    location: "https://maps.app.goo.gl/68kgAyGyJ7a16H4v5",
    longitude: "90.404530",
    latitude: "23.798603",
    level: "3rd",
    description: "Located in the heart of Banani.",
    terms: "Terms and conditions apply.",
    status: true,
  },
  {
    branchName: "Mirpur Branch",
    propertyId: 5,
    ownerId: 2,
    area: "Mirpur",
    city: "Dhaka",
    country: "Bangladesh",
    images: [
      {
        link: "https://png.pngtree.com/thumb_back/fh260/background/20230714/pngtree-3d-rendering-of-restaurant-and-cafe-interior-design-image_3885659.jpg",
        precedence: 1,
      },
      {
        link: "https://png.pngtree.com/thumb_back/fh260/background/20230817/pngtree-tables-set-at-a-restaurant-image_13032060.jpg",
        precedence: 2,
      },
    ],
    amenities: [
      {
        icon: "https://www.svgrepo.com/show/61290/wifi-logo.svg",
        name: "Wifi",
      },
      {
        icon: "https://www.svgrepo.com/show/236545/basketball.svg",
        name: "Playground",
      },
    ],
    amenity: ["Wifi", "Playground"],
    location: "https://maps.app.goo.gl/mirpurLocation",
    longitude: "23.8042",
    latitude: "90.3654",
    level: "2nd",
    description: "A spacious branch with modern amenities.",
    terms: "Please read terms before booking.",
    status: true,
  },
  {
    branchName: "Uttara Center",
    propertyId: 6,
    ownerId: 4,
    area: "Uttara",
    city: "Dhaka",
    country: "Bangladesh",
    images: [
      {
        link: "https://images.rawpixel.com/image_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvcC0zNTktZmVsaXhydXNzZWxsc2F3LTQ0LmpwZw.jpg",
        precedence: 1,
      },
      {
        link: "https://png.pngtree.com/thumb_back/fh260/background/20230703/pngtree-d-illustration-of-architectural-design-for-a-coffee-shop-lounge-with-image_3788822.jpg",
        precedence: 2,
      },
    ],
    amenities: [
      {
        icon: "https://www.svgrepo.com/show/339667/washer.svg",
        name: "Washer and dryer",
      },
      {
        icon: "https://www.svgrepo.com/show/489318/parking.svg",
        name: "Parking",
      },
    ],
    amenity: ["Washer and dryer", "Parking"],
    location: "https://maps.app.goo.gl/QxrbX9nUZ9mbsUYW8",
    longitude: "90.3523129",
    latitude: "23.8022742",
    level: "8th",
    description: "Conveniently located near major attractions.",
    terms: "All visitors must follow guidelines.",
    status: true,
  },
  {
    branchName: "Tejgaon Business Hub",
    propertyId: 7,
    ownerId: 3,
    area: "Tejgaon",
    city: "Dhaka",
    country: "Bangladesh",
    images: [
      {
        link: "https://png.pngtree.com/thumb_back/fh260/background/20230712/pngtree-d-illustration-of-architecturally-designed-coffee-shop-with-banner-and-menu-image_3853464.jpg",
        precedence: 1,
      },
      {
        link: "https://img.freepik.com/premium-photo/empty-banner-mockups-front-coffee-shop_863013-109697.jpg",
        precedence: 2,
      },
    ],
    amenities: [
      {
        icon: "https://www.svgrepo.com/show/18559/swimming-pool.svg",
        name: "Swimming pool",
      },
      {
        icon: "https://www.svgrepo.com/show/61290/wifi-logo.svg",
        name: "Security",
      },
    ],
    amenity: ["Wifi", "Security"],
    location: "https://maps.app.goo.gl/C3RRVcC6r7Vxu9V49",
    longitude: "90.379314",
    latitude: "23.875407",
    level: "6th",
    description: "An ideal spot for businesses and startups.",
    terms: "Terms must be agreed upon prior to booking.",
    status: true,
  },
  {
    branchName: "Motijheel Tower",
    propertyId: 8,
    ownerId: 2,
    area: "Motijheel",
    city: "Dhaka",
    country: "Bangladesh",
    images: [
      {
        link: "https://t4.ftcdn.net/jpg/08/67/69/85/360_F_867698508_bGQCwC0LzZnNhI7svu3KSQk9aJhaX7pd.jpg",
        precedence: 1,
      },
      {
        link: "https://png.pngtree.com/thumb_back/fw800/background/20240522/pngtree-abstract-blur-coffee-shop-or-cafe-restaurant-interior-image_15683717.jpg",
        precedence: 2,
      },
    ],
    amenities: [
      {
        icon: "https://www.svgrepo.com/show/236545/basketball.svg",
        name: "Playground",
      },
      {
        icon: "https://www.svgrepo.com/show/61290/wifi-logo.svg",
        name: "Security",
      },
    ],
    amenity: ["Playground", "Security"],
    location: "https://maps.app.goo.gl/F5VbAfFM8Pff7U5w6",
    longitude: "90.392746",
    latitude: "23.757056",
    level: "12th",
    description: "Perfect for corporate offices in the heart of the city.",
    terms: "All guests must register upon entry.",
    status: true,
  },
  {
    branchName: "Bashundhara Convention",
    propertyId: 9,
    ownerId: 5,
    area: "Bashundhara",
    city: "Dhaka",
    country: "Bangladesh",
    images: [
      {
        link: "https://img.freepik.com/premium-photo/coffee-shop-cafe-restaurant-interior-blur-background-generative-ai_874904-41255.jpg",
        precedence: 1,
      },
      {
        link: "https://www.shutterstock.com/image-photo/empty-wood-table-blur-interior-600nw-2477812091.jpg",
        precedence: 2,
      },
    ],
    amenities: [
      {
        icon: "https://www.svgrepo.com/show/68796/conference-hall.svg",
        name: "Conference Hall",
      },
      {
        icon: "https://www.svgrepo.com/show/311854/cafeteria.svg",
        name: "Cafeteria",
      },
    ],
    amenity: ["Conference Hall", "Cafeteria"],
    location: "https://maps.app.goo.gl/sE71tZWxS2YrpGPN8",
    longitude: "90.417387",
    latitude: "23.734641",
    level: "Ground",
    description: "Great for large conventions and corporate events.",
    terms: "Event booking required in advance.",
    status: true,
  },
  {
    branchName: "Baridhara Embassy",
    propertyId: 10,
    ownerId: 5,
    area: "Baridhara",
    city: "Dhaka",
    country: "Bangladesh",
    images: [
      {
        link: "https://www.fsrmagazine.com/wp-content/uploads/2024/03/TableRestaurant-552x312.jpg",
        precedence: 1,
      },
      {
        link: "https://img.freepik.com/premium-photo/blur-coffee-shop-cafeteria-image-background-use_1111209-34638.jpg",
        precedence: 2,
      },
    ],
    amenities: [
      {
        icon: "https://www.svgrepo.com/show/114082/lockers.svg",
        name: "Package lockers",
      },
      {
        icon: "https://www.svgrepo.com/show/489318/parking.svg",
        name: "Parking",
      },
    ],
    amenity: ["Package lockers", "Parking"],
    location: "https://maps.app.goo.gl/VD73ikLu99AmimMe9",
    longitude: "90.431345",
    latitude: "23.825387",
    level: "1st",
    description: "Ideal for diplomatic meetings and conferences.",
    terms: "Security protocols apply.",
    status: true,
  },
  {
    branchName: "Mohammadpur Gateway",
    propertyId: 11,
    ownerId: 6,
    area: "Mohammadpur",
    city: "Dhaka",
    country: "Bangladesh",
    images: [
      {
        link: "https://img.freepik.com/premium-photo/abstract-blur-defocus-coffee-shop-cafe-restaurant-interior-background_1235831-89671.jpg",
        precedence: 1,
      },
      {
        link: "https://png.pngtree.com/thumb_back/fw800/background/20240522/pngtree-abstract-blur-coffee-shop-or-cafe-restaurant-interior-background-image_15683837.jpg",
        precedence: 2,
      },
    ],
    amenities: [
      {
        icon: "https://www.svgrepo.com/show/339667/washer.svg",
        name: "Washer and dryer",
      },
      {
        icon: "https://www.svgrepo.com/show/61290/wifi-logo.svg",
        name: "Wifi",
      },
    ],
    amenity: ["Washer and dryer", "Wifi"],
    location: "https://maps.app.goo.gl/Pc894hDzzzBAvLKk8",
    longitude: "90.4197229",
    latitude: "23.8003305",
    level: "2nd",
    description: "Relaxed ambiance with outdoor options.",
    terms: "First-come, first-served seating.",
    status: true,
  },
  {
    branchName: "Paltan Central",
    propertyId: 8,
    ownerId: 2,
    area: "Paltan",
    city: "Dhaka",
    country: "Bangladesh",
    images: [
      {
        link: "https://img.freepik.com/premium-photo/table-restaurant-with-few-people-background_881067-796.jpg",
        precedence: 1,
      },
      {
        link: "https://img.freepik.com/premium-photo/wooden-table-front-blurred-lights-restaurant-background_875722-14641.jpg",
        precedence: 2,
      },
    ],
    amenities: [
      {
        icon: "https://www.svgrepo.com/show/61290/wifi-logo.svg",
        name: "Parking",
      },
      {
        icon: "https://www.svgrepo.com/show/455913/laundry-service.svg",
        name: "Laundry",
      },
    ],
    amenity: ["Parking", "Laundry"],
    location: "https://maps.app.goo.gl/XnDNUjqDpk154ZGUA",
    longitude: "90.362137",
    latitude: "23.763297",
    level: "1st",
    description: "A convenient spot for quick meals and shopping.",
    terms: "No outside food allowed.",
    status: true,
  },
  {
    branchName: "Khilgaon Hub",
    propertyId: 9,
    ownerId: 5,
    area: "Khilgaon",
    city: "Dhaka",
    country: "Bangladesh",
    images: [
      {
        link: "https://png.pngtree.com/thumb_back/fh260/background/20230712/pngtree-d-illustration-of-architectural-design-for-coffee-shop-bar-with-banner-image_3853372.jpg",
        precedence: 1,
      },
      {
        link: "https://img.freepik.com/premium-photo/black-cafe-with-bar-counter-sign-that-says-coffee-it_818261-3222.jpg",
        precedence: 2,
      },
    ],
    amenities: [
      {
        icon: "https://www.svgrepo.com/show/288102/air-conditioning-air-conditioner.svg",
        name: "Air Conditioning",
      },
      {
        icon: "https://www.svgrepo.com/show/61290/wifi-logo.svg",
        name: "Wifi",
      },
    ],
    amenity: ["Air Conditioning", "Wifi"],
    location: "https://maps.app.goo.gl/fBqpc3SSr3CSMEtm9",
    longitude: "90.410108",
    latitude: "23.736253",
    level: "4th",
    description: "A well-cooled spot with modern amenities.",
    terms: "Guests should be respectful of shared spaces.",
    status: true,
  },
  {
    branchName: "Shyamoli Mall",
    propertyId: 11,
    ownerId: 6,
    area: "Shyamoli",
    city: "Dhaka",
    country: "Bangladesh",
    images: [
      {
        link: "https://img.freepik.com/premium-photo/coffee-shop-with-black-wall-wooden-counter-with-coffee-machine-middle_920594-30495.jpg",
        precedence: 1,
      },
      {
        link: "https://img.freepik.com/premium-photo/coffee-shop-with-black-counter-coffee-machine_795881-2451.jpg",
        precedence: 2,
      },
    ],
    amenities: [
      {
        icon: "https://www.svgrepo.com/show/450831/elevator.svg",
        name: "Elevator",
      },
      {
        icon: "https://www.svgrepo.com/show/61290/wifi-logo.svg",
        name: "Wifi",
      },
    ],
    amenity: ["Elevator", "Wifi"],
    location: "https://maps.app.goo.gl/kcRjsdsB5LkzYDKy6",
    longitude: "90.3645658",
    latitude: "23.7730768",
    level: "7th",
    description: "A shopping haven with easy access for all.",
    terms: "No pets allowed.",
    status: true,
  },
  {
    branchName: "Old Town Spot",
    propertyId: 10,
    ownerId: 5,
    area: "Old Town",
    city: "Dhaka",
    country: "Bangladesh",
    images: [
      {
        link: "https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-d-illustration-of-coffee-shop-s-front-order-counter-and-interior-image_3785558.jpg",
        precedence: 1,
      },
      {
        link: "https://image.shutterstock.com/image-illustration/cafe-shop-restaurant-design-minimalist-600w-1347986534.jpg",
        precedence: 2,
      },
    ],
    amenities: [
      {
        icon: "https://www.svgrepo.com/show/288102/air-conditioning-air-conditioner.svg",
        name: "Air Conditioning",
      },
      { icon: "https://www.svgrepo.com/show/452760/cafe.svg", name: "Cafe" },
    ],
    amenity: ["Air Conditioning", "Cafe"],
    location: "https://maps.app.goo.gl/JgLa2zgf4W5m32PQ9",
    longitude: "90.426406",
    latitude: "23.704992",
    level: "Ground",
    description: "Experience the charm of Dhaka's Old Town.",
    terms: "Respect the historic artifacts.",
    status: true,
  },
];

const homeDataFaker = [
  {
    title: "Promotional Banner",
    subtitle: "Promotional Banner",
    type: "PROPERTY",
    group: "RESTAURANT",
    pattern: "promotional-banner",
    content: [
      {
        bannerImage:
          "https://t3.ftcdn.net/jpg/03/24/73/92/360_F_324739203_keeq8udvv0P2h1MLYJ0GLSlTBagoXS48.jpg",
        linkTo: 3,
      },
      {
        bannerImage:
          "https://img.freepik.com/premium-vector/free-vector-white-vintage-restaurant-logo_883906-2549.jpg",
        linkTo: 1,
      },
    ],
    signature: 1,
    precedency: 1,
    status: true,
  },
  {
    title: "Feature Restaurant",
    subtitle: "All The Ryserved Feature Restaurant",
    type: "PROPERTY",
    group: "RESTAURANT",
    pattern: "slider",
    signature: 2,
    precedency: 2,
    status: true,
  },
  {
    title: "ads Banner",
    subtitle: "ads Banner",
    type: "OTHER",
    group: "RESTAURANT",
    pattern: "banner-ads",
    content: [
      {
        bannerImage:
          "https://t3.ftcdn.net/jpg/03/24/73/92/360_F_324739203_keeq8udvv0P2h1MLYJ0GLSlTBagoXS48.jpg",
        linkTo: 3,
      },
    ],
    signature: 3,
    precedency: 3,
    status: true,
  },
  {
    title: "Exclusive At Ryserved",
    subtitle: "All the Exclusive at Ryserved",
    type: "PROPERTY",
    group: "RESTAURANT",
    pattern: "slider",
    signature: 4,
    precedency: 4,
    status: true,
  },
  {
    title: "Top Restaurant",
    subtitle: "chef's special mentions",
    type: "PROPERTY",
    group: "RESTAURANT",
    pattern: "promotional-logo",
    signature: 5,
    precedency: 5,
    status: true,
  },
  {
    title: "Spotlight Restaurant",
    subtitle: "chef's special mentions",
    type: "FOOD",
    group: "RESTAURANT",
    pattern: "food-promotion",
    signature: 6,
    precedency: 6,
    status: true,
  },
];

const categoryFaker = [
  {
    categoryName: "Snacks",
    images:
      "https://www.shutterstock.com/image-photo/small-portion-food-on-big-260nw-157078907.jpg",
    priority: 1,
    categoryType: "FOOD",
    status:true
  },
  {
    categoryName: "Chicken Wings",
    images:
      "https://www.shutterstock.com/image-photo/crispy-fried-chicken-food-made-260nw-2453523369.jpg",
    priority: 1,
    categoryType: "FOOD",
    status:true
  },
  {
    categoryName: "Fried Chicken",
    images:
      "https://www.shutterstock.com/image-photo/fried-chicken-paper-bucket-isolated-260nw-2110658288.jpg",
    priority: 3,
    categoryType: "FOOD",
    status:true
  }
];
const foodFaker = [
  {
    categoryId:1,
    name:"BBQ Meat Machine Pizza",
    images:["https://images.deliveryhero.io/image/fd-bd/Products/4061162.jpg??width=400"],
    propertyId:2,
    price:[{"small":560,"Large":950,"Medium":760}],
    description:"Topped with beef & chicken both with freshly cut vegetables, cheese & in a soft pizza dough",
    status:true
},
{
  categoryId:1,
  name:"Cheddar Cream Pizza",
  images:["https://images.deliveryhero.io/image/fd-bd/Products/7202738.jpg??width=400"],
  propertyId:2,
  price:[{"small":360,"Large":750,"Medium":660,"Family":1050}],
  description:"Salty, Cheese, Chicken, Cult favourite.",
  status:true
},
{
  categoryId:3,
  name:"Chicken Tongue Slayer",
  images:["https://images.deliveryhero.io/image/fd-bd/Products/Pizza%20Burg%20-%20Mirpur/1046077.jpg?width=%s"],
  propertyId:2,
  price:[{"TK":360}],
  description:"1 pc - Cheesy burger loaded with tender chicken and 25% naga sauce, cooked to perfection for a delicious bite",
  status:true
}
];
module.exports = {
  ownerFaker,
  amenityFaker,
  cuisineFaker,
  listingsFaker,
  brachFaker,
  homeDataFaker,
  categoryFaker,
};
